name: Build RPM packages for PostgreSQL-16 using Self-hosted Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout PGRPM Repository
      uses: actions/checkout@v2
      with:
        repository: qasimtahir91/pgrpm
        path: pgrpm

    - name: Update changelog in SPEC file
      run: |
        current_date=$(date +"%a %b %d %Y")
        spec_file="pgrpm/rpm/redhat/main/non-common/postgresql-16/main/postgresql-16.spec"
        sed -i "s/\*.*Qasim Tahir <qasim.m@bitnine.net> - 16.3.0-1/\* $current_date Qasim Tahir <qasim.m@bitnine.net> - 16.3.0-1/g" $spec_file
        echo "Date in the %changelog section has been updated to: $current_date"

    - name: Navigate to EL-8 directory
      run: cd pgrpm/rpm/redhat/16/postgresql-16/EL-8

    - name: Remove old Agens Repo code/zip
      run: |
        rm -rf pgrpm/rpm/redhat/16/postgresql-16/EL-8/postgresql-16.3
        rm -rf pgrpm/rpm/redhat/16/postgresql-16/EL-8/postgresql-16.3.zip

    - name: Clone PostgreSQL Repository into EL-8 directory
      run: git clone https://github.com/qasimtahir91/postgresql-16.3.git pgrpm/rpm/redhat/16/postgresql-16/EL-8/postgresql-16.3

    - name: Create ZIP archive
      run: |
        cd pgrpm/rpm/redhat/16/postgresql-16/EL-8
        chmod +x postgresql-16.3/configure
        zip -r pgrpm/rpm/redhat/16/postgresql-16/EL-8/postgresql-16.3.zip pgrpm/rpm/redhat/16/postgresql-16/EL-8/postgresql-16.3

    - name: Remove old directories
      run: rm -rf ~/rpm16/ ~/rpmbuild/

    - name: Build the RPM
      run: |
        cd pgrpm/rpm/redhat/16/postgresql-16/EL-8
        make build16

    - name: Notify build completion
      run: echo "Build Created ... DONE !!"
